/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package events

import (
	testexecutionv1 "github.com/kubeshop/testkube-operator/api/testexecution/v1"
	testsuiteexecutionv1 "github.com/kubeshop/testkube-operator/api/testsuiteexecution/v1"
)

// Event data
type Event struct {
	// UUID of event
	Id       string         `json:"id"`
	Resource *EventResource `json:"resource"`
	// ID of resource
	ResourceId         string                                   `json:"resourceId"`
	Type_              *EventType                               `json:"type"`
	TestExecution      *testexecutionv1.TestExecution           `json:"testExecution,omitempty"`
	TestSuiteExecution *testsuiteexecutionv1.TestSuiteExecution `json:"testSuiteExecution,omitempty"`
	// cluster name of event
	ClusterName string `json:"clusterName,omitempty"`
	// environment variables
	Envs map[string]string `json:"envs,omitempty"`
}
