// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubeshop/testkube-operator/client/tests/v3 (interfaces: Interface)

// Package tests is a generated GoMock package.
package tests

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v3 "github.com/kubeshop/testkube-operator/apis/tests/v3"
	v1 "k8s.io/api/core/v1"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInterface) Create(arg0 *v3.Test) (*v3.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*v3.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInterface)(nil).Create), arg0)
}

// CreateTestSecrets mocks base method.
func (m *MockInterface) CreateTestSecrets(arg0 *v3.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestSecrets", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTestSecrets indicates an expected call of CreateTestSecrets.
func (mr *MockInterfaceMockRecorder) CreateTestSecrets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestSecrets", reflect.TypeOf((*MockInterface)(nil).CreateTestSecrets), arg0)
}

// Delete mocks base method.
func (m *MockInterface) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInterfaceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInterface)(nil).Delete), arg0)
}

// DeleteAll mocks base method.
func (m *MockInterface) DeleteAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockInterfaceMockRecorder) DeleteAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockInterface)(nil).DeleteAll))
}

// DeleteByLabels mocks base method.
func (m *MockInterface) DeleteByLabels(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByLabels", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByLabels indicates an expected call of DeleteByLabels.
func (mr *MockInterfaceMockRecorder) DeleteByLabels(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByLabels", reflect.TypeOf((*MockInterface)(nil).DeleteByLabels), arg0)
}

// Get mocks base method.
func (m *MockInterface) Get(arg0 string) (*v3.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*v3.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfaceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterface)(nil).Get), arg0)
}

// GetCurrentSecretUUID mocks base method.
func (m *MockInterface) GetCurrentSecretUUID(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSecretUUID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSecretUUID indicates an expected call of GetCurrentSecretUUID.
func (mr *MockInterfaceMockRecorder) GetCurrentSecretUUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSecretUUID", reflect.TypeOf((*MockInterface)(nil).GetCurrentSecretUUID), arg0)
}

// GetSecretTestVars mocks base method.
func (m *MockInterface) GetSecretTestVars(arg0, arg1 string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretTestVars", arg0, arg1)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretTestVars indicates an expected call of GetSecretTestVars.
func (mr *MockInterfaceMockRecorder) GetSecretTestVars(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretTestVars", reflect.TypeOf((*MockInterface)(nil).GetSecretTestVars), arg0, arg1)
}

// List mocks base method.
func (m *MockInterface) List(arg0 string) (*v3.TestList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(*v3.TestList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInterfaceMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInterface)(nil).List), arg0)
}

// ListByNames mocks base method.
func (m *MockInterface) ListByNames(arg0 []string) ([]v3.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNames", arg0)
	ret0, _ := ret[0].([]v3.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNames indicates an expected call of ListByNames.
func (mr *MockInterfaceMockRecorder) ListByNames(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNames", reflect.TypeOf((*MockInterface)(nil).ListByNames), arg0)
}

// ListLabels mocks base method.
func (m *MockInterface) ListLabels() (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels")
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockInterfaceMockRecorder) ListLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockInterface)(nil).ListLabels))
}

// LoadTestVariablesSecret mocks base method.
func (m *MockInterface) LoadTestVariablesSecret(arg0 *v3.Test) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTestVariablesSecret", arg0)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTestVariablesSecret indicates an expected call of LoadTestVariablesSecret.
func (mr *MockInterfaceMockRecorder) LoadTestVariablesSecret(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTestVariablesSecret", reflect.TypeOf((*MockInterface)(nil).LoadTestVariablesSecret), arg0)
}

// Update mocks base method.
func (m *MockInterface) Update(arg0 *v3.Test) (*v3.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(*v3.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInterfaceMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterface)(nil).Update), arg0)
}

// UpdateTestSecrets mocks base method.
func (m *MockInterface) UpdateTestSecrets(arg0 *v3.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestSecrets", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTestSecrets indicates an expected call of UpdateTestSecrets.
func (mr *MockInterfaceMockRecorder) UpdateTestSecrets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestSecrets", reflect.TypeOf((*MockInterface)(nil).UpdateTestSecrets), arg0)
}
